[project]
name = "home5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.0",
    "pydantic>=2.12.3",
    "requests>=2.32.5",
    "scikit-learn==1.6.1",
    "uvicorn[standard]>=0.38.0",
]
